name: 01 - Building Blocks

on:
  workflow_dispatch:

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello, World!"

  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Succeeded step # Nome atualizado
        run: |
          echo "I will succeed!" # Mensagem atualizada
          exit 0 # <- A MUDANÇA PRINCIPAL!
      - name: Say goodbye
        run: echo "Goodbye!"