name: 02 - Workflow Events

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: echo "O evento que disparou este workflow foi: ${{ github.event_name }}"
